### ISSUE TITLE
failure fetching info for vobject

### ISSUE THREAD

**Issue by dunn** [tdsmith/homebrew-pypi-poet#10]
Might have to do with the unusual version (https://pypi.python.org/pypi/vobject/0.8.1c)?

All I get is
```ruby
  resource "vobject" do
    url ""
     ""
  end
```

**Comment by tdsmith** [comment]
Yeah, 0.8.1c looks like a release candidate to 0.8.1, which is marked released but hidden on pypi without downloads, and the API and website do different things when the apparently newest release is hidden: http://chat-logs.dcpython.org/day/pypa/2015-05-22#04.31.57.tdsmith

poet could try to do something clever here but hopefully these cases are rare.
