### ISSUE TITLE
poet crashes if no sdist available

### ISSUE THREAD

**Issue by tdsmith** [tdsmith/homebrew-pypi-poet#29]

**Comment by Kriechi** [comment]
Same here - any known workarounds? I think if possible we should just skip dependencies without sdist's?

**Comment by tdsmith** [comment]
No workarounds; this would be unusual for packages distributed on pypi,
which is the driving use case.

**Comment by alfiepates** [comment]
I've been bitten by this bug today: 

I'd advocate for two things: 

1. Better error reporting when this _does_ happen. The error message that's spat out is pretty cryptic for non-python users. 

2. The ability to force poet to generate a resource stanza _anyway_, with non-sdist-y packages commented out: I've come across a couple of libraries in PyPI which are only distributed as wheels (for some ridiculous reason), with the source being available as a tarball from GitHub, etc. It'd be useful to have the tooling still work even if a couple of dependences aren't available automatically: I can enter them manually if I need to.
