### ISSUE TITLE
Consider using virtualenv_install_with_resources for --formula

### ISSUE THREAD

**Issue by zmwangx** [tdsmith/homebrew-pypi-poet#31]
Code is easy to fix — just need to update `FORMULA_TEMPLATE ` in `poet.py`, and `virtualenv_install_with_resources` is usually enough. However, as far as I can tell we do lose some flexibility like the ability to pass additional options to `setup.py`. Do you think it's worthwhile?

**Comment by tdsmith** [comment]
Yes, this is worth doing.
