### ISSUE TITLE
Example of poet autodeployment with Travis CI

### ISSUE THREAD

**Issue by jbarlow83** [tdsmith/homebrew-pypi-poet#52]
This is an FYI for the poet maintainers, not a bug. I thought you might be interested in how I set up automated deployment to my homebrew tap. Perhaps it's useful to someone else as an example.

I use TravisCI to run build tests and deploy to PyPI if the build is tagged and passes. After deployment, the macOS build will run poet (twice) to generate the necessary information for a homebrew formula, and then automatically update the homebrew formula on Github.

Access to the homebrew tap on Github is through a Github token for a Github account with push access that I created for doing the updates. (In theory one should be able to avoid the second account using Github's ssh deploy keys, but that route does not work for me since the version of ssh available on Travis CI's macOS images is crippled somehow.)

The relevant files are:
https://github.com/jbarlow83/OCRmyPDF/blob/master/.travis.yml
https://github.com/jbarlow83/OCRmyPDF/blob/master/.travis/osx_brew.sh
https://github.com/jbarlow83/OCRmyPDF/blob/master/.travis/autobrew.py

I find this works much better for me than manually updating the formula because I do a few releases per month.

It also illustrates a possible shortcoming in poet's feature set: the inability to specify dependencies on *non-Python* system libraries that are required to build. (Or maybe this is a conscious decision.)

**Comment by tdsmith** [comment]
Thanks for the heads-up; this is cool. This wasn't an anticipated use case but making the poet output require less hand-editing could be worth doing.
