### ISSUE TITLE
poet sometimes fails to select latest version because its method of accessing PyPI returns the wrong version

### ISSUE THREAD

**Issue by jbarlow83** [tdsmith/homebrew-pypi-poet#53]
I ran into this issue while using poet. I'm fairly confident it's not your fault, but I thought you'd be interested in following the issue:
https://github.com/pypa/warehouse/issues/1996

**Comment by tdsmith** [comment]
Thanks for the report! I've seen something like this before; I suspect fastly caches HTTP/1.1 and HTTP/2 traffic separately, which explains the different result in the browser. Anyway, it should become consistent eventually.
