### ISSUE TITLE
Packages in private pip repositories are not supported

### ISSUE THREAD

**Issue by dzavalkinolx** [tdsmith/homebrew-pypi-poet#55]
I have a private package hosted in our company's artifactory. I have a `extra-index-url` set in my pip config but homebrew-pypi-poet doesn't respect `extra-index-url`. It just has a hardcoded package resolution to `https://pypi.io/pypi/{}/json` in https://github.com/tdsmith/homebrew-pypi-poet/blob/master/poet/poet.py#L80.

**Comment by tdsmith** [comment]
Thanks for opening an issue. That sounds right; there's no attempt to interpret pip's configuration. The goal of this project is to facilitate contributions to the public Homebrew repositories and so pypi is the only package repository in scope.

**Comment by dzavalkinolx** [comment]
What's wrong with having private homebrew repositories and why you don't wish to support them? I understand that in the end this is your tool and you can do whatever you want of course... But since it is linked on the Homebrew tools for python developers page and Homebrew team has nothing against creating private taps I don't see why officially suggested tool for generating formula resources shouldn't support private pip packages...

**Comment by tdsmith** [comment]
> What's wrong with having private homebrew repositories

Nothing at all. It's just a distinct set of problems that I don't personally have. It also seems to arise mostly in contexts where people who aren't me are being paid to work on things :) and my personal preference is to not spend much of my OSS time in that space.

**Comment by americanhanko** [comment]
My company is also having this problem. Artifactory's Python package data is formatted in XML, but return roughly the same information about the packages as the data stored in JSON by PyPI. I'm not sure it would be that difficult to support a custom PyPI URL – @tdsmith would you be willing to merge a pull request if this feature was added? CC: @dzavalkinolx

**Comment by tdsmith** [comment]
No, but please feel free to fork.
