### ISSUE TITLE
Move this repo into the Homebrew organisation?

### ISSUE THREAD

**Issue by commitay** [tdsmith/homebrew-pypi-poet#63]
How would you feel about moving this repo into the Homebrew organisation? You would still have the same permissions to the repo.

This would allow for maintenance to be shared amongst the Homebrew maintainers and also improve its visibility.

Something to discuss if you are okay with the move would be if you are happy with it continuing to be published to PyPI using your personal account or if you would want to transfer it to a Homebrew account.

**Comment by tdsmith** [comment]
If you'd like it, you're welcome to it.

Creating a new pypi role account for the Travis auto-deploy secret would probably make sense.

**Comment by commitay** [comment]
@tdsmith I've invited you to the Homebrew org `pypi-poet` team which should allow you to transfer the repo.

Created `Homebrew` user on PyPI https://pypi.org/user/Homebrew/

**Comment by commitay** [comment]
@tdsmith Apologies, the invite got canceled. You've been re-invited. Please let me know if you have any problems transferring the repo. Thanks!

cc @MikeMcQuaid

**Comment by commitay** [comment]
@tdsmith gentle ping on this.
